version: '3.8'
services:
  app:
    build: .
    image: prnie/python-flask-api:latest
    ports:
      - "5000:5000"
    environment:
      - REDIS_ENDPOINT=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  test:
    build: .
    command: pytest
    environment:
      - REDIS_ENDPOINT=redis
      - REDIS_PORT=6379
    volumes:
      - .:/usr/src/app
    depends_on:
      - app
      - redis